repos:
  - repo: local
    hooks:
      - id: commit-msg
        name: commit-msg
        entry: ./.hooks/commit-msg.py
        language: python
        stages:
          - commit-msg

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json

  - repo: local
    hooks:
      - id: activate-venv
        name: activate venv
        entry: echo hello
        language: system
        run: source ./venv/bin/activate
      - id: check-format
        name: check format
        entry: make -s format_staged
        language: system
      - id: check-lint
        name: check lint
        entry: make -s lint_staged
        language: system
